// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoers.Api.Data;

#nullable disable

namespace ToDoers.Api.Data.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20250726133030_SeedTags")]
    partial class SeedTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoers.Api.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Urgent"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Code Review"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Refactor"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Debug"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Deployment"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Research"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Errands"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Learning"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Blocked"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Recurring"
                        },
                        new
                        {
                            Id = 15,
                            Name = "QuickWin"
                        });
                });

            modelBuilder.Entity("ToDoers.Api.Entities.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("ToDoers.Api.Entities.Todo", b =>
                {
                    b.HasOne("ToDoers.Api.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });
#pragma warning restore 612, 618
        }
    }
}
